# Generated by Django 4.2 on 2023-04-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2023', '2023'), ('2022', '2022')], max_length=50)),
                ('branch', models.CharField(choices=[('ECE', 'ECE'), ('CSE', 'CSE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('CHEM', 'CHEM'), ('EEE', 'EEE')], max_length=50)),
                ('placed', models.BooleanField(default='FALSE')),
                ('placed_on', models.BooleanField()),
                ('package', models.CharField(choices=[('2.5-4.5', '2.5-4.5'), ('4.5-6', '4.5-6'), ('6-9', '6-9'), ('9-12', '9-12'), ('12-18', '12-18'), ('18-24', '18-24'), ('more', 'more')], max_length=50)),
            ],
        ),
    ]
