# Generated by Django 4.2 on 2023-04-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='branch',
            field=models.CharField(choices=[('ECE', 'ECE'), ('CSE(select-for-similar-brances-like-csm-Ai-IT)', 'CSE(select-for-similar-brances-like-csm-Ai-IT)'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('CHEM', 'CHEM'), ('EEE', 'EEE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='package',
            field=models.CharField(blank=True, choices=[('2.5-4.5', '2.5-4.5'), ('4.5-6', '4.5-6'), ('6-9', '6-9'), ('9-12', '9-12'), ('12-18', '12-18'), ('18-24', '18-24'), ('more', 'more')], max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='placed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='details',
            name='placed_on',
            field=models.CharField(blank=True, choices=[('IT(software)', 'IT(software)'), ('core', 'core')], max_length=50),
        ),
    ]
